### ISSUE TITLE
Support for multiple output formats

### ISSUE THREAD

**Issue by naporin0624** [node-libraries/wasm-image-optimization#1]
Thank you for developing this wonderful library.

I have thought of a feature that would allow me to change the format of an image by looking at the accept header, like CloudflareImages does!

I was wondering if it would be possible to have a flexible way to select the output format for this? Is this possible?

**Comment by SoraKumo001** [comment]
@naporin0624 

The library now supports png and jpeg conversion, so you can change the output format to suit your requirements.

**Comment by naporin0624** [comment]
@SoraKumo001 

Thank you so much!
It's the best!

https://github.com/node-libraries/wasm-image-optimization/commit/0046d4912e9a15e086bae7bdb0ced04b0166db5e
