### ISSUE TITLE
Support for rotating Exif information

### ISSUE THREAD

**Issue by cafeins** [node-libraries/wasm-image-optimization#3]
Thank you for the wonderful library

When there is rotation information in the Exif data of an image, 
the orientation of the image may change between before and after optimization. 
Is it possible to address this issue?

**Comment by SoraKumo001** [comment]
@cafeins 
Exif rotation is now reflected.

**Comment by cafeins** [comment]
@SoraKumo001 
Thank you for your support.
I tried it, but after the version upgrade, the following error occurs, and image optimization fails.
Do you know what the cause might be?

```
TypeError: Cannot perform %TypedArray%.prototype.copyWithin on a detached ArrayBuffer
    at Uint8Array.copyWithin (<anonymous>)
    at Vl (worker.js:4:40073)
    at wasm://wasm/0097e5c2:wasm-function[52]:0x1967
    at wasm://wasm/0097e5c2:wasm-function[1483]:0x11ae8b
    at wasm://wasm/0097e5c2:wasm-function[2073]:0x19718d
    at wasm://wasm/0097e5c2:wasm-function[2009]:0x18b045
    at wasm://wasm/0097e5c2:wasm-function[2000]:0x189a4e
    at wasm://wasm/0097e5c2:wasm-function[1996]:0x1892aa
    at wasm://wasm/0097e5c2:wasm-function[2031]:0x18df56
    at wasm://wasm/0097e5c2:wasm-function[2261]:0x1dcda9
```

**Comment by SoraKumo001** [comment]
@cafeins 
We tried converting the image we had but could not reproduce it here.

**Comment by cafeins** [comment]
I have attached the image that resulted in an error.

![79e197d5-3b8e-4220-836c-24ca46b02a5e](https://github.com/node-libraries/wasm-image-optimization/assets/157496959/f8d46e0e-9f1b-41c5-b856-8a863b32d139)

**Comment by SoraKumo001** [comment]
@cafeins 
It works locally, so the available memory of Workers may have been exceeded.
Currently it is not possible to rotate data of that size.

**Comment by cafeins** [comment]
@SoraKumo001 
Understood, thank you for addressing the rotation issue.

**Comment by SoraKumo001** [comment]
@cafeins 
Rotation is now applied after resizing.
If you adjust the output size with a parameter, it will work with Workers.
