### ISSUE TITLE
Feature to read image size

### ISSUE THREAD

**Issue by yahiro07** [node-libraries/wasm-image-optimization#4]
(Originally I wrote this issue in Japanese, but I rewrote it in English for benefits.)

Hi.
I'm thankful for the library since it can resize images in cloudflare workers.
Thank you.

The optimization function works very well.
However, I have a requirement I'd like to apply custom resizing process.
In the process, I want to read the original size of the image.

I experimentally added a helper function to get image dimension.

https://github.com/yahiro07/wasm-image-optimization

It would be helpful for the use-cases like below.

- Return original image when the original size is smaller than the output.
- Control whether the output should contain or cover the specified size.
- Reduces juggies by stepping resize for larger scaling ratio.

I'm happy if this feature merged.
I'd like to make a PR if you OK.

Thanks.

**Comment by fineshop** [comment]
You can try [@cf-wasm/photon](https://www.npmjs.com/package/@cf-wasm/photon), a fork of [@silvia-odwyer/photon](https://www.npmjs.com/package/@silvia-odwyer/photon).
It has functions like get_width, get_height and many more.

**Comment by yahiro07** [comment]
@fineshop
Thank you. Your library seems to fit my requirements.
I'd like to try it out.

**Comment by yahiro07** [comment]
It worked very well. Thanks.

**Comment by yahiro07** [comment]
I'd like to close this issue.
Actually, I've reconsiderated that doing custom resizing is beyond the scope of this single-featured library.
I'm going to use [@cf-wasm/photon](https://www.npmjs.com/package/@cf-wasm/photon), for these specialized use-cases. 
Thanks

**Comment by fineshop** [comment]
> It worked very well. Thanks.

Glad to hear.
Credit goes to [silvia-odwyer/photon](https://github.com/silvia-odwyer/photon).
